import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200 flex items-center justify-center min-h-screen`}
      >
        <div 
          className="bg-white shadow-2xl overflow-hidden relative"
          style={{
            width: '390px',
            height: '844px',
            opacity: 1,
            transform: 'rotate(0deg)',
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
